### ISSUE TITLE
spring

### ISSUE THREAD

**Issue by lixinxinlove** [brianway/springmvc-mybatis-learning#4]
没有Spring 的吗？  加油

**Comment by brianway** [comment]
建议仔细阅读我的 README:

> 这套笔记整体偏入门和应用，适合快速上手，对底层实现和机理并未做过多分析。关于 spring 源码的学习笔记,可以参考我的另一个仓库spring-learning

https://github.com/brianway/spring-learning

**Comment by lixinxinlove** [comment]
好的 谢谢
