### ISSUE TITLE
mapper代理方法的疑惑

### ISSUE THREAD

**Issue by skyyann** [brianway/springmvc-mybatis-learning#5]
最近拜读了您写的文章，略有收获，但发现了一个问题：[mybatis学习笔记(4)-开发dao方法.md](https://github.com/brianway/springmvc-mybatis-learning/blob/master/mybatis/mybatis%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0(4)-%E5%BC%80%E5%8F%91dao%E6%96%B9%E6%B3%95.md)这篇文章中的mapper代理方法，mapper.xml和mapper.java是在一个包里吧？在SqlMapConfig.xml里面是这样的`<mapper resource="mapper/UserMapper.xml" />`，但是报错了，错误原因Cause:java.io.IOException: Could not find resource mapper/UserMapper.xml。只有把包名写全才行。如：`<mapper resource="com/iot/mybatis/mapper/UserMapper.xml" />`。我使用的mybatis版本是3.4.4，求解惑！！！！我还给您发邮件了，请您看看

**Comment by brianway** [comment]
好久没做，忘记了，我简单看了下。

在这个项目的 `sourcecode/mybatis/config/` 文件夹下，有 `mapper` 文件夹和 `SqlMapConfig.xml` 文件，这里的配置应该是相对路径，用的应该是这个 `mapper` 里的 UserMapper.xml。

在包全名下，也有个 UserMapper.xml 的文件，后续的代码可能用的是这个。两处应该都留着，因为这个是系列博客，而源码只有一个文件夹，所以可能前面几篇文章和后面的文章里的 UserMapper 不是同一个。

应该是这个原因，比较忙，没仔细看。
