### ISSUE TITLE
请问逆向mybatis中的Generatorsqlmap这个类是做什么用的，源码里面没有

### ISSUE THREAD

**Issue by zyxnine9** [brianway/springmvc-mybatis-learning#8]

**Comment by zyxnine9** [comment]
请问逆向mybatis中执行逆行工程的时候，Generatorsqlmap这个类是做什么用的，源码中没有

**Comment by brianway** [comment]
运行逆向工程的入口吧，逆向工程相当于一个黑盒子，函数库，你调用它是需要写代码的吧，不然怎么生成你需要的文件呢？

**Comment by fooderLong** [comment]
今天才看到邮件，逆向生成mybatis文件使用了一个开源工具，并没有放入到我自己的代码里面来^\/^
  

 

 ------------------ 原始邮件 ------------------
  发件人: "魏楚阳";<notifications@github.com>;
 发送时间: 2017年11月7日(星期二) 晚上10:44
 收件人: "brianway/springmvc-mybatis-learning"<springmvc-mybatis-learning@noreply.github.com>;
 抄送: "Subscribed"<subscribed@noreply.github.com>; 
 主题: Re: [brianway/springmvc-mybatis-learning] 请问逆向mybatis中的Generatorsqlmap这个类是做什么用的，源码里面没有 (#8)

 

 
运行逆向工程的入口吧，逆向工程相当于一个黑盒子，函数库，你调用它是需要写代码的吧，不然怎么生成你需要的文件呢？
